steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clouddeveloper-299318/bitbucket.org/sachindramaharjan/service/web-project:$SHORT_SHA', '.']
  dir: 'web'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/clouddeveloper-299318/bitbucket.org/sachindramaharjan/service/web-project:$SHORT_SHA']

  